module(name = "gerrit-oauth-provider")

bazel_dep(name = "rules_jvm_external", version = "6.10")
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "oauth_plugin_deps",
    artifacts = [
        "com.nimbusds:nimbus-jose-jwt:10.9.1",
        "com.sap.cloud.security:java-security:3.6.0",
    ],
    duplicate_version_warning = "error",
    excluded_artifacts = [
        # com_sap_cloud_security:java_security depends on commons-io.
        # Gerrit core already provides commons-io, so exclude it here to
        # avoid bundling it into the plugin and prevent duplicate classes
        # or version skew at runtime in Gerrit's plugin classloader.
        "commons-io:commons-io",
        # com.sap.cloud.security.xsuaa:token-client depends on caffeine cache,
        # and slf4j-api. Gerrit core already provides caffeine cache and
        # slf4j-api, so exclude it here to  avoid bundling it into the plugin
        # and prevent duplicate classes or version skew at runtime in Gerrit's
        # plugin classloader.
        "com.github.ben-manes.caffeine:caffeine",
        "org.slf4j:slf4j-api",
    ],
    fail_if_repin_required = True,
    fail_on_missing_checksum = True,
    fetch_sources = True,
    lock_file = "//:oauth_plugin_deps.lock.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    version_conflict_policy = "pinned",
)
use_repo(maven, "oauth_plugin_deps")
