load("@com_googlesource_gerrit_bazlets//:gerrit_plugin.bzl", "gerrit_plugin_library")

gerrit_plugin_library(
    name = "jwt",
    srcs = glob(["*.java"]),
    ext_deps = ["com.nimbusds:nimbus-jose-jwt"],
    plugin = "oauth",
    visibility = ["//plugins/oauth:__subpackages__"],
    deps = ["//plugins/oauth/src/main/java/com/googlesource/gerrit/plugins/oauth/utils"],
)
