load(
    "@com_googlesource_gerrit_bazlets//:gerrit_plugin.bzl",
    "gerrit_plugin_ext_test_deps",
    "gerrit_plugin_tests",
)
load("//plugins/oauth:provider.bzl", "CORE")

gerrit_plugin_ext_test_deps(
    name = "sapias_test_deps",
    ext_deps = [
        "com.sap.cloud.security.java:api",
        "com.sap.cloud.security.java:security",
        "com.sap.cloud.security:env",
        "com.sap.cloud.security.xsuaa:token-client",
    ],
    plugin = "oauth",
)

gerrit_plugin_tests(
    name = "sapias_tests",
    srcs = glob(["*.java"]),
    deps = CORE + [
        ":sapias_test_deps",
        "//plugins/oauth/src/main/java/com/googlesource/gerrit/plugins/oauth/sapias",
    ],
)
