include_defs('//bucklets/maven_jar.bucklet')

maven_jar(
  name = 'gson',
  id = 'com.google.code.gson:gson:2.3.1',
  sha1 = 'ecb6e1f8e4b0e84c4b886c2f14a1500caf309757',
  license = 'Apache2.0',
)

maven_jar(
  name = 'guava',
  id = 'com.google.guava:guava:18.0',
  sha1 = 'cce0823396aa693798f8882e64213b1772032b09',
  license = 'Apache2.0',
)
