include_defs('//bucklets/maven_jar.bucklet')

VER = '2.10.2'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = '4086f90b4d7be9101e84e8e3e76262496d2e12fe',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)
